# Generated by Django 3.2.4 on 2023-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230209_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Proporção recomendada: 1:1 (quadrada).', upload_to='products'),
        ),
    ]
