# Generated by Django 3.2.4 on 2023-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.jpg', help_text='Proporção recomendada: 1:1 (quadrada).', upload_to='products'),
        ),
    ]
