# Generated by Django 3.2.4 on 2023-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20230223_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='texto alternativo da imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_homepage',
            field=models.BooleanField(default=True, verbose_name='está na home'),
        ),
    ]
