# Generated by Django 3.2.4 on 2023-02-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20230110_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'dados da empresa', 'verbose_name_plural': 'dados da empresa'},
        ),
    ]
