# Generated by Django 3.2.4 on 2023-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(help_text='Resolução recomendada: 1920x550.', upload_to='banners/'),
        ),
    ]
