# Generated by Django 3.2.4 on 2023-02-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(help_text='Resolução recomendada: 1920x600.', upload_to='banners/'),
        ),
    ]
