# Generated by Django 3.2.4 on 2023-02-23 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='homepage_priority',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='prioridade na home (maior = primeiro)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_in_homepage',
            field=models.BooleanField(default=True, verbose_name='está na home?'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(help_text='Resolução recomendada: 1920x600.', upload_to='banners/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='texto alternativo da imagem'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='título'),
        ),
    ]
