# Generated by Django 3.2.4 on 2023-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20230223_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='texto alternativo da foto'),
        ),
    ]
