# Generated by Django 3.2.4 on 2023-02-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'pergunta frequente', 'verbose_name_plural': 'perguntas frequentes'},
        ),
    ]
