version: "3.9"

services:
  gcloud:
    image: google/cloud-sdk:412.0.0
    volumes:
      - gcp-creds:/creds
      - .:/code

    working_dir: /code
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds: